/** FORJA IA — Identidad de versión de FORJA IA.
 *
 * El módulo evoluciona por entregas numeradas (semver): cada actualización
 * que se empaqueta lleva un ZIP nuevo forja-ia-vX.Y.Z.zip. Este archivo es
 * la fuente de verdad de qué versión hay instalada: la UI puede pintarla en
 * Ajustes y el changelog (CAMBIOS.md) explica qué cambió en cada una.
 *
 * Regla: FORJA_ID (modelo.ts) es estable desde el rebrand v4.1.0 (en su vida
 * PRISMA-D1 el id era prism:d1-diseno); entre versiones, solo cambia esto.
 */

export const VERSION_FORJA = "4.7.2";

/** Nombre en clave de la versión, para la ficha de Ajustes. */
export const NOMBRE_VERSION_FORJA = "Experience Compiler";

/** Qué trae esta versión, una línea por novedad (la pinta la UI). */
export const NOVEDADES_FORJA: string[] = [
  "v4.7.2 · EXPERIENCE COMPILER: recetas compatibles por familia, Experience Manifest como fuente única de verdad, modo espacial mínimo protegido por Performance Gate y datos no declarados nunca se presentan como hechos reales.",
  "v4.7.0 · LA PÁGINA, NO EL HERO — auditoría completa del módulo (581 ficheros): v4.6 compiló CÓMO se ve la experiencia con un detalle extraordinario (familias, recetas, heroes, primitivas, objeto 3D) y dejó sin decidir QUÉ contiene la página. RecetaExperiencia no tenía un solo campo de secciones, los datos del brief se tiraban y ningún QA medía densidad de contenido. v4.7 cierra ese hueco con 3 ideas nuevas (G-I) y 9 correcciones de cableado — todo determinista, todo a coste cero.",
  "v4.7.0 · G — PLANO DE CONTENIDO (plano-contenido.ts): inventario de 13 secciones con slots y mínimos verificables, 9 plantillas por vertical, 3 niveles de detalle (borrador/producción/showcase) que mueven a la vez secciones, piezas, líneas objetivo y techo de tokens. extraerHechos() saca precios, teléfonos, correos, horarios, ciudad y cantidades del brief — datos que hasta ahora se tiraban — y los HECHOS AÑADEN secciones: dos precios declarados exigen la sección de precios, un horario exige ubicación.",
  "v4.7.0 · H — QA DE DETALLE (qa-detalle.ts): 24 métricas de densidad (secciones reales, palabras visibles, piezas por colección, estados en el CSS, breakpoints, imágenes con aspect-ratio, SVG frente a emojis, anclas conectadas, texto de relleno, bloques clonados) auditadas contra el plano de contenido, con puntuación 0-100 y 13 tipos de hallazgo con corrección propuesta. Corre como fase 6d del núcleo: lo que falta se convierte en un ENCARGO QUIRÚRGICO de una sola llamada («amplía, no regeneres») con rollback honesto si la ampliación no mejora.",
  "v4.7.0 · I — ICONOGRAFÍA E IMAGEN COMPILADAS (iconos.ts): 24 iconos SVG de trazo con currentColor y grosor coherente (mismo patrón que primitivas.ts: el Codificador selecciona, no dibuja paths a mano), elegidos por sector con elegirIconos(); figuraPlaceholder() con aspect-ratio fijo para que el layout nunca salte al cargar; cifras con font-variant-numeric:tabular-nums. Sustituye al emoji-como-icono y al <img> sin dimensión que el QA de detalle marcaba como defecto.",
  "v4.7.0 · CORRECCIÓN — CORPUS DE SEÑALES: hasta v4.6 seleccionarExperiencia() decidía la dirección creativa con SOLO el mensaje crudo; la ficha del Diseñador y el ADN visual (personalidad, sensación, lenguaje, prohibiciones) no entraban, así que el ADN del Diseñador y el de experiencia podían contradecirse. corpusDeSenales() en maqueta.ts compone brief + estructura de la ficha + ADN + feedback; en el núcleo, el ADN 2.0 recién definido entra como señal.",
  "v4.7.0 · CORRECCIÓN — EL AJUSTE YA NO SE EVAPORA: «Ajusta: quita el objeto 3D, menos movimiento» no re-decidía la experiencia — el contrato determinista seguía exigiéndolo y ganaba porque es más largo y viene con CSS. El feedback entra ahora en el corpus de señales (se repite para que pese) y de verdad cambia el contrato.",
  "v4.7.0 · CORRECCIÓN — ANTI-REPETICIÓN CON DATOS REALES: penalizacionComposicion() se calculaba ANTES de elegir hero y cards, con `(\"\", spatial, \"\")` — su consejo era inerte. Ahora corre después con los valores reales y su sección llega POR FIN al contrato que ve el maquetador (antes solo la leía director2).",
  "v4.7.0 · CORRECCIÓN — HISTORIAL PERSISTENTE: DepsMvp acepta historialComposicion (simétrico a memoriaAprendizaje) y lo restaura con cargarHistorial() al arrancar. Hasta v4.6 el historial vivía solo en memoria del proceso: en cualquier despliegue serverless obtenerHistorial() devolvía [] en cada generación y la anti-repetición §13 era decorativa.",
  "v4.7.0 · CORRECCIÓN — recompilarDesdeDna() YA NO DEGRADA A MINIMAL: llamaba seleccionarExperiencia(\"\"); sin señales, la familia caía a minimal y la receta a modern_minimal — tocar un radius en el panel podía borrar la familia spatial de la página. Ahora el mensaje original viaja en OpcionesExperiencia.mensajeOriginal y manda.",
  "v4.7.0 · CORRECCIÓN — VERTICALES LOCALES ALINEADOS: panadería, barbería, floristería y compañía vivían en la señal comercial de experience-dna.ts pero no en la tabla VERTICALES de familias-experiencia.ts —la que de verdad decide la familia—, así que caían en «general» → minimal. Alineadas, y un negocio local ya no cae en la familia quieta por defecto.",
  "v4.7.0 · CORRECCIÓN — PRESUPUESTO RECALIBRADO: la fase implementation (la que produce la página completa) subió del 38% al 46% del presupuesto global, y los totales por complejidad de 24k/40k/64k a 32k/56k/88k. La llamada del Codificador ahora fija maxTokens según el nivel de detalle en vez de heredar el defecto del rol.",
  "v4.7.0 · REGRESIÓN: 314 aserciones sin red, 0 fallos — v4.4 (52/52) · v4.5 (86/86) · v4.6 (86/86) · v4.7 nueva (90/90, integracion/adapter-test/verificacion-v47.mjs) — todas contra el bundle real reconstruido. TypeScript estricto: 0 errores. El bundle es superconjunto exacto del de v4.6: ninguna de las 349 exportaciones anteriores desaparece; 373 exportaciones totales.",

  "v4.6.0 · EL TALLER QUE APRENDE (ideas A-F de la hoja de ruta): v4.5 decidió la experiencia DETERMINISTAMENTE; v4.6 le entrega al motor los COMPONENTES ya compilados, el OBJETO 3D forjado, el QA del movimiento MEDIDO, el contrato EDITABLE por humanos, la ARENA que compara FAMILIAS y el CIRCUITO DE APRENDIZAJE del Genoma. La dirección creativa no solo se decide gratis: ahora también se EJECUTA gratis y MEJORA con cada generación.",
  "v4.6.0 · A — PRIMITIVAS COMPILADAS (el mayor ahorro restante): biblioteca de 8 bloques listos (RevealGroup, TiltCard, MagneticCTA, FloatingMetric, SpotlightCard, ParallaxLayer, StickyStory, Marquee) con HTML+CSS completos, responsive, toques ≥44px y reduced-motion YA auditados de fábrica + scripts capados (tilt 8°, imán 12px, spotlight, parallax rAF). El Codificador SELECCIONA y parametriza; NO re-inventar. Cada primitiva reutilizada sale gratis y nace auditada — coste marginal 0 tokens.",
  "v4.6.0 · B — LEARNING LOOP DEL GENOMA: la huella de cada generación se guarda AHORA también con su RESULTADO (score + veredicto). Con 20-30 generaciones, recomendacionesAprendidas() pasa de «penalizar lo reciente» a «recomendar lo que ganó»: DESTACAR/EVITAR con evidencia («HERO_SPLIT ganó 91/100 en 5 generaciones»). Los ajustes alimentan elegirHero (+2/-2) y la Arena de familias (+1.5/-1.5). Memoria inyectable y serializable (el host la persiste).",
  "v4.6.0 · C — OBJETO 3D CSS PARAMÉTRICO REAL: 8 formas forjadas (Monolito, Orbe, Capas flotantes, Tarjeta doblada, Anillo orbital, Torre isométrica, Cubo giratorio, Constelación) en HTML+CSS 3D puro, ~2 KB cada una, 0 three.js, 0 librerías. Elegidas por familia+señales+anti-repetición, con aria-hidden, tokens de experiencia y reduced-motion resueltos. El «central 3D object» del doc §29 sale SIEMPRE bien — también para una panadería.",
  "v4.6.0 · D — MOTION QA MEDIDO: se PARSEA el CSS real (reglas selector{declaración}) y se verifica la escala §9 POR DURACIÓN: nada fuera de 150-1600ms salvo ambiente (infinite), stagger presente cuando el plan lo pide y guard de reduced-motion que apague de verdad. Hallazgos con evidencia (selector + declaración + ms) y parches deterministas append-only: guard canónica, overrides de duración capados a 8 reglas, utilidad .forja-stagger. Corre en el núcleo (fase 6c) tras el QA de experiencia.",
  "v4.6.0 · E — CONTRATO DE EXPERIENCIA EXPORTABLE/EDITABLE (JSON): SeleccionExperiencia → schema estable forja.experiencia@1 (exportarContrato/serializarContrato). El host EDITA familia/hero/intensidad/modo/profundidad/elevación/blur/radius/use3d/pesoObjeto, valida (validarContrato) y RE-COMPILA el pipeline completo con 0 tokens (aplicarEdicionContrato): tokens CSS, objeto, primitivas y planes regenerados coherentes. El eslabón del panel «Elige la experiencia».",
  "v4.6.0 · F — ARENA ENTRE FAMILIAS: las 3 visiones corren EN 3 FAMILIAS DISTINTAS (asignarFamiliasArena: natural+vecinas por señales/aprendizaje). El juez de coherencia (determinista, vocabulario §12 por familia) puntúa si cada maqueta HABLA el lenguaje de su familia. El ganador deja lección al Genoma: «la familia spatial funcionó para saas: coherencia 8/10» — la elección de familia APRENDE en vez de quedarse congelada.",
  "v4.6.0 · La MAQUETA también forja: mensajeMaqueta lleva ahora el HTML exacto del objeto 3D, el HTML de ejemplo de cada primitiva, la CSS determinista completa y el script capado — la maqueta sale RICA (objeto + superficies + movimiento) incluso para verticales sin señales fuertes. El Codificador recibe lo mismo por el núcleo.",

  "v4.5.0 · EL MOTOR DE EXPERIENCIA (correcciones moderno-3D §1-§35): FORJA deja de ser «un generador que evita lo genérico» y pasa a ser un MOTOR DE DIRECCIÓN CREATIVA — la cadena INTENCIÓN → FAMILIA → RECETA → REPRESENTACIÓN → PLAN ESPACIAL → PLAN DE MOVIMIENTO → HERO → CARDS → RESPONSIVE → TOKENS se decide DETERMINISTAMENTE y viaja al modelo como contrato. El LLM ejecuta; no improvisa. Montado SOBRE la eficiencia v4.4 sin reemplazarla (§32).",
  "v4.5.0 · FIN DEL SESGO EDITORIAL (§1/§3/§23): el orden [editorial, espacial, cinematica] de las visiones de respaldo era una preferencia implícita. Ahora 10 FAMILIAS DE EXPERIENCIA (spatial, immersive, product, cinematic, interactive, 3d-showcase, modular, editorial, minimal, dashboard) se eligen por intención, y editorial SOLO domina con intención editorial real (blog/revista/artículo/noticias). Regla de seguridad: moderno/premium/futurista/3D/inmersivo/interactivo empuja a spatial/product/cinematic/interactive/3d-showcase ANTES que editorial.",
  "v4.5.0 · EXPERIENCE DNA (§2): el ADN ahora habla de espacio y superficie — visual/composition/spatial/motion/interaction/surface/object con profundidad, capas, perspectiva, elevación, blur y objeto focal. Sintetizado gratis desde la petición y visible en la traza con sus razones.",
  "v4.5.0 · EXPERIENCE RECIPES (§4): 7 recetas estructuradas (SPATIAL_PRODUCT, CINEMATIC_PRODUCT, IMMERSIVE_PORTFOLIO, INTERACTIVE_SAAS, 3D_SHOWCASE, CREATIVE_STUDIO, MODERN_MINIMAL). El modelo no inventa la composición: EJECUTA la receta.",
  "v4.5.0 · SPATIAL ENGINE (§5): la página deja de ser section→container→cards y puede ser una ESCENA — fondo, retícula, ambiente, objeto focal, tipografía, UI flotante, métricas y navegación con z-index SEMÁNTICO, perspectiva y parallax por capa.",
  "v4.5.0 · HERO ENGINE (§6): 10 tipos de hero (HERO_SPATIAL, HERO_3D_OBJECT, HERO_PRODUCT, HERO_CINEMATIC, HERO_INTERACTIVE, HERO_SPLIT, HERO_FLOATING_CARDS, HERO_FULLSCREEN, HERO_SCROLL_REVEAL, HERO_MINIMAL) con composiciones canónicas. PROHIBIDO asumir hero centrado + h1 + párrafo + botón.",
  "v4.5.0 · CARD SYSTEM (§7): 14 variantes semánticas (CARD_FLOATING, CARD_TILT, CARD_MAGNETIC, CARD_GLASS, CARD_3D, CARD_STACKED, CARD_SPOTLIGHT…) cada una con comportamiento y propósito. Glass disciplinado: máximo una variante y solo si el ADN pide blur.",
  "v4.5.0 · MOTION ENGINE (§8/§9): lenguaje de 16 primitivas con intensidad 0-4 (static → immersive) y tiempos POR CATEGORÍA: micro 150-300ms · componente 250-600ms · reveal 500-1000ms · escena 800-1600ms · ambiente continuo. La regla 200-300ms era correcta para microinteracciones, no filosofía global. prefers-reduced-motion SIEMPRE.",
  "v4.5.0 · PUERTA DE RENDIMIENTO (§10/§20): 2D/2.5D/3D/WebGL se eligen con criterio (WebGL solo si el beneficio justifica costo/peso/performance) y la cascada WebGL → 3D/CSS → 2.5D → 2D degrada AUTOMÁTICAMENTE. 3D CSS con preserve-3d: el 90% del efecto, 0 librerías, 0 KB — más profesional Y más barato.",
  "v4.5.0 · EDITORIAL BIAS DETECTOR (§11/§12): editorialScore con las ponderaciones exactas del doc (textDensity×0.25 + readingFlow×0.20 + imageRectangles×0.15 − motion − depth − interacción − spatial) MÁS 7 métricas de experiencia. No es estética: es una señal técnica; y el objetivo es la COHERENCIA con el ADN, no el máximo.",
  "v4.5.0 · ANTI-REPETICIÓN (§13): el motor guarda la huella de las últimas composiciones (hero, cards, motion, spatial, navegación) y PENALIZA repeticiones en los últimos 3 proyectos — no más «hero espacial + 3 cards flotantes + parallax» en todas las páginas.",
  "v4.5.0 · BIBLIOTECA POSITIVA (§14): 20 patrones «SÍ usar» (floating product, oversized typography, technical grid, scroll choreography, magnetic CTA, tilt card, sticky storytelling…) con cuándo y cómo. La IA necesita alternativas concretas, no solo prohibiciones.",
  "v4.5.0 · CONTRATO DE EXPERIENCIA en PROMPT_MAQUETA y Codificador (§15/§16): EXPERIENCE DNA + RECIPE + SPATIAL PLAN + MOTION PLAN + HERO TYPE + SURFACE SYSTEM + INTERACTION SYSTEM + RESPONSIVE EXPERIENCE. Separación neta Design Direction vs Code Generation.",
  "v4.5.0 · DESIGN TOKENS DE EXPERIENCIA (§17/§18): --radius-*, --depth-1..4, --perspective-*, --motion-*, --shadow-soft/floating/deep, --surface-* — generados desde el ADN y entregados como CSS determinista (tokens + escenario + movimiento + cards) que el Codificador incluye tal cual.",
  "v4.5.0 · RESPONSIVE EXPERIENCE PLAN (§19): qué se mantiene/reduce/reordena/elimina/transforma por breakpoint (desktop 3D+4 cards+parallax → tablet reducido → móvil objeto+1 card sin camera movement). Responsive como experiencia, no solo width:100%.",
  "v4.5.0 · QA DE EXPERIENCIA + PATCH-FIRST (§21/§22): editorial bias, coherencia espacial/movimiento/profundidad, riqueza de interacción, calidad del hero, consistencia de superficies y responsive se AUDITAN. Sesgo editorial alto NO regenera la página: parche determinista (objeto focal, cards flotantes, depth, scroll reveal) con contenido intacto y reduced-motion respetado.",
  "v4.5.0 · REFERENCE DNA (§24/§25): las referencias se convierten en PRINCIPIOS (dark canvas, technical grid, oversized typography, central 3D object, floating UI…) especificados por dimensión — nunca en píxeles. «No copio esta página: extraigo su lenguaje y creo una experiencia nueva.»",
  "v4.5.0 · El Diseñador ya no prescribe «beneficios (3 tarjetas)» en landing y su prompt incluye la biblioteca positiva completa. Registro con experiencia (familia/receta/hero/métricas) y cuenta de la experiencia en la respuesta al usuario (§29-31: el resultado se explica en términos de experiencia).",

  "v4.4.0 · EL TALLER EFICIENTE (plan §22/23/24/25/26/28): la capa de eficiencia completa — presupuesto global de tokens por fases (planning/design/implementation/qa/repair/reserve), caché multinivel de 6 niveles, compilador de contexto, enrutador determinista, salida temprana y Token ROI. Cada generación ahora muestra cuánto ahorró.",
  "v4.4.0 · PRESUPUESTO GLOBAL DE TOKENS (presupuesto-tokens.ts): el techo ya no es solo por llamada (v4.2) sino por GENERACIÓN, repartido en las 6 fases del plan. La complejidad de la petición (determinista: longitud, edición, alcance) y el perfil de coste calibran el total (simple 24k · media 40k · compleja 64k). El Codificador nunca pide más de lo que su fase puede pagar: pedir lo impagable era pagar un corte.",
  "v4.4.0 · CACHÉ MULTINIVEL (cache-multinivel.ts): los 6 niveles exactos del plan — L1 respuesta exacta, L2 ficha, L3 decisión arquitectónica (el ADN de la misma petición no se paga dos veces), L4 patrón visual, L5 parche, L6 resultado de QA. LRU por nivel con stats y cascada a la capa persistente del host.",
  "v4.4.0 · COMPILADOR DE CONTEXTO (compilador-contexto.ts, plan §23): las reglas del proyecto, memoria, conocimiento y el brief se DEDUPLICAN, puntúan por relevancia contra la intención y se recortan a un techo antes de viajar al modelo. Contexto compacto, relevante y priorizado — las prohibiciones duras (fallos confirmados) SIEMPRE viajan. Nunca enviar todo el proyecto cuando basta un componente.",
  "v4.4.0 · ENRUTADOR DETERMINISTA (enrutador-determinista.ts, plan §22): Detect → Classify → Deterministic Fix? → YES → Patch. lang, viewport, charset, title, alt, ARIA/label, noopener, tabindex, reduced-motion y overflow se corrigen GRATIS con parches seguros — sin tocar el diseño. El LLM es el último recurso mecánico, no el primero.",
  "v4.4.0 · SALIDA TEMPRANA (salida-temprana.ts, plan §26): Generate → QA → Good enough? → YES → STOP. Score determinista ≥ 92 con 0 críticos/0 avisos para en la primera pasada; ≥ 84 tras una iteración. Antes de gastar un modelo, se prueban los parches deterministas. El bucle de mejora ya no gasta 3 iteraciones cuando la primera aprueba.",
  "v4.4.0 · TOKEN ROI (token-roi.ts, plan §28): cada operación registra operación · tokens · llamadas · resultado · mejora de QA y calcula quality gain / tokens. Con el tiempo el sistema aprende qué operaciones merecen tokens, qué parches son repetitivos y qué pasos pueden ser deterministas — con recomendaciones accionables por evidencia medida.",
  "v4.4.0 · ENVOLTORIO EFICIENTE (eficiencia.ts): caché L1 + presupuesto + ROI encadenados en un único LlamadaModelo. El host envuelve su adaptador una vez y TODO el pipeline (núcleo, Arena, bucle) se vuelve eficiente sin tocar al adaptador-resiliente. DepsMvp.cache acepta la capa persistente del host; deps.sinEficiencia desactiva todo para pruebas A/B.",
  "v4.4.0 · CORRECCIONES: la llamada del ADN ahora declara rol y techo (viaja bien en failover y presupuesto); el nº de llamadas del registro es el REAL medido por el ROI (antes se sumaban estimaciones de la Arena); la entrada del bundle (adapter-test/entrada.mjs) viaja en el zip y el bundle se reconstruye con esbuild en un comando.",
  "v4.3.1 · EL TALLER A MEDIDA (PC y móvil): navegación 100% interna — las tres entradas de la barra abren el Estudio en la misma pestaña con deep-link /forja?tab=… (cero window.open) — y responsive completo: pestañas deslizables en móvil, contenedor h-dvh, táctiles ≥ 32 px y 0 desbordes horizontales auditados a 375×667 y 1280×800.",
  "v4.3.0 · EL TALLER ABIERTO: el Estudio FORJA IA vive DENTRO del host (ruta /forja) con su mismo tema claro/oscuro y acento — sin pestañas sueltas ni temas ajenos. Ficha → Maqueta, ADN 2.0 con exportadores, Jueces con evidencia y Anti-genérico corren ahí mismo con el bundle real del módulo.",
  "v4.3.0 · CATÁLOGO COMPLETO a la vista: el Estudio abre con el mapa íntegro de opciones del módulo (núcleo, ADN, jueces, anti-genérico, Director, Arena, bucle de mejora, 5 memorias, Genoma, perfiles de coste y fuentes semilla) y dice dónde vive cada una — nada de PRISMA-D1 queda escondido.",
  "v4.3.0 · PRESUPUESTO POR ROL EN AJUSTES: los techos de tokens del motor (Diseñador/Codificador/Revisor) se editan desde la UI del host y viajan de verdad en cada llamada del Estudio vía techoTokens() — la mejora v4.2 ahora se toca sin código.",
  "v4.3.0 · BUNDLE DEL MOTOR AMPLIADO (142 exportaciones): adn-visual, adn2, exportadores-adn, anti-genérico, jueces 2.0, evaluador de éxito, bucle de mejora, perfiles, fuentes, seguridad web, genoma y design system se sirven al navegador junto al núcleo y el blindaje v4.1/v4.2.",
  "v4.2.0 · PRESUPUESTO DE TOKENS POR ROL en la ConfigForja (maxTokensPorRol): el núcleo resuelve el techo con techoTokens() y viaja en cada llamada — si tu proveedor corta en 8k aunque pidas más, ahora se le pide lo que SÍ puede dar, por rol y sin tocar código.",
  "v4.2.0 · SEGUNDO CINTURÓN ANTI-TRUNCAMIENTO a nivel núcleo (continuacion-nucleo.ts): detección estructural GRATIS de salidas rotas (cercados impares, <html> sin cerrar, <style>/<script> abiertos) + continuación exacta. El corte que el adaptador no pudo cerrar no llega ya al Revisor: se cierra aquí y se ahorra la regeneración entera (la llamada más cara del pipeline).",
  "v4.2.0 · TELEMETRÍA CONECTADA A OBSERVABILIDAD: crearTelemetriaForja(registro) convierte los eventos del adaptador en telemetría del registro de generación (reintentos, failovers, continuaciones, tokens, latencias). El evento nuevo exito reporta latencia y tokens de cada llamada; textoConsultas() suma el blindaje de red.",
  "v4.2.0 · CACHÉ DE GENERACIONES POR HASH (cache-fichas.ts): la misma petición (mensaje + código + reglas + config, invalidada por versión) no paga dos veces la ficha del Diseñador ni la maqueta inicial. LRU en memoria lista, y cacheEnCascada() para añadir la capa persistente que cada host prefiera.",
  "v4.2.0 · SALUD DE PROVEEDORES POR LATENCIA (salud-proveedores.ts): el adaptador alimenta un libro de salud con evidencia medida (EWMA de latencia, fallos consecutivos, enfriamiento con backoff) y los SUPLENTES del failover se reordenan por rendimiento real — el primario, que es tu elección, nunca se toca.",
  "v4.2.0 · El Lab cablea todo: llamador por generación con registro de observabilidad serializado al log, caché compartida del proceso y salud global. Panel del motor v4.2 en el preview para ver el blindaje funcionando en vivo.",
  "v4.1.0 · REBRAND: PRISMA-D1 pasa a ser FORJA IA — en la forja el metal bruto se convierte en obra. Nuevo id público forja:ia-diseno (antes prism:d1-diseno): re-selecciona FORJA en el selector; la configuración por rol se conserva.",
  "v4.1.0 · ADAPTADOR RESILIENTE (un solo archivo, adaptador-resiliente.ts): failover en cadena por rol + max_tokens por rol (16.384 en el Codificador — una página completa no cabe en 4k, y el corte por max_tokens pasa igual de pagado que de gratis) + reintentos con backoff exponencial y jitter en errores de red.",
  "v4.1.0 · ANTI-TRUNCAMIENTO por finish_reason: motivo-parada.ts traduce el campo del proveedor (length / stop / max_tokens / content_filter en los tres protocolos). Si la salida quedó corta («length»), el adaptador pide CONTINUACIÓN (máx. 2) y concatena; si sigue corta, los chequeos estáticos y el Revisor lo recogen antes de entregar.",
  "v4.1.0 · El rol viaja en cada llamada (núcleo, Estudio y bucle de mejora): el adaptador sabe qué techo pedir y qué suplentes usar. Telemetría de reintentos y failover por onEvento, lista para enchufar a observabilidad.",
  "v4.1.0 · Marca nueva: logo del yunque forjado (SVG escalable + favicon + iconos PWA), Laboratorio renombrado FORJA-IA-Laboratorio.html con el yunque en la cabecera y chip v4.1.0.",
  "v4.0.1 · Transporte a prueba de proxies: el chat del Lab ya no muere con «el servidor no respondió» — POST devuelve {id} al instante y los eventos se leen por sondeo corto (route v4.0.1 + cliente actualizado).",
  "v4.0.1 · La maqueta en la pestaña Vista llena el panel completo (antes salía aplastada en una tira de ~150 px) y el distintivo «MAQUETA · FORJA IA» ya no sale duplicado.",
  "v4.0.1 · El atajo «¿qué fuentes tienes?» vuelve a responder al instante (la regex no reconocía esa formulación).",
  "Plan maestro OpenDesign + Stitch ejecutado de una pieza: FORJA IA queda como CEREBRO creativo, OpenDesign como CUERPO (vía adaptador con runtime local de respaldo) y Stitch solo como REFERENCIA de experiencia. Mapa de integración completo en docs/INTEGRACION-MAPA.md.",
  "ADN VISUAL 2.0: de 4 a 14 dimensiones (identidad, composición, tipografía, color, espaciado, movimiento, representación, interacción, referencias, anti-patrones, accesibilidad…). El ADN ahora se convierte en DESIGN.md, tokens.css, reglas de critique, restricciones del Codificador y criterios de la Arena (exportadores-adn.ts). Migración v3→v4 automática: nada se rompe.",
  "DIRECTOR CREATIVO 2.0: las 3 visiones divergen por REPRESENTACIÓN, ESTRUCTURA, NARRATIVA, INTERACCIÓN y COMPOSICIÓN (arquetipos editorial/espacial/cinematográfica/cartográfica/conversacional/modular), no por color o fuente. Cada visión explica qué representa, qué prioriza, qué riesgo tiene y a quién beneficia.",
  "ARENA 2.0 como laboratorio: modos económico (2 visiones/1 juez), profesional (3/3+3 jueces+fusión) y experimental (modelos por equipo), gobernados por perfiles de coste FREE/SMART/ARENA/LAB con presupuesto de llamadas declarado.",
  "JUECES CON EVIDENCIA: el panel ya no da solo notas — cada juez produce qué funciona / qué falla / qué conservar (y el de originalidad: patrones genéricos, diferenciadores, riesgos) partiendo de EVIDENCIA FÍSICA determinista. 5 jueces opcionales nuevos: accesibilidad, conversión, responsive, coherencia de sistema y performance.",
  "ANTI-GENERIC ENGINE 2.0 en 3 capas: determinista (existente), visual (proxies estructurales de composición: simetría, monotonía, densidad, focal point, repetición) y semántica («¿podría cambiarse el logo y venderse como plantilla?») con puntuación compuesta ponderada.",
  "REVISOR VISUAL AUTOMÁTICO con veredicto PASS/WARN/FAIL y hallazgos enriquecidos: problema + evidencia + gravedad + CAUSA PROBABLE + CORRECCIÓN PROPUESTA.",
  "BUCLE AUTÓNOMO DE MEJORA (máx 3 iteraciones): generar → inspeccionar → criticar → corregir → comparar → ¿mejoró? sí: continuar / no: REVERTIR. Score determinista; nunca un bucle infinito.",
  "MEMORIA 2.0 en 5 memorias: proyecto, usuario, global, EXPERIMENTAL y FALLOS («esta última es especialmente importante»): los fallos confirmados se convierten en prohibiciones duras y viajan SIEMPRE al prompt.",
  "GENOMA VISUAL: cada Arena deja lecciones (destacar/conservar/evitar) que se consolidan en patrones, anti-patrones, experimentos, reglas o referencias. Arena → lecciones → memoria → nueva generación: evolución real, no apuntes muertos.",
  "CANVAS tipo Stitch + VOZ SEMÁNTICA: «hazlo más exclusivo» se traduce a decisiones (densidad ↓, espacio ↑, jerarquía ↑, repetitivos ↓) — NUNCA gradientes o glassmorphism automáticos. Intérprete determinista en español, sin modelo.",
  "MEJORA MI PÁGINA: diagnóstico determinista del código existente (sistema actual, ADN detectado, genericidad), propuesta de rediseño con evidencia, variante comparada por score y solo se aplica si GANA.",
  "REFERENCIAS abstractas: URL/HTML/imagen/descripción/design system → atributos → inspiración → ADN. Nunca copiar una referencia; los riesgos se convierten en anti-patrones.",
  "OBSERVABILIDAD + BENCHMARK + MÉTRICAS: cada generación deja un registro completo (modelo, skills, iteraciones, coste); 10 casos de benchmark (SaaS, e-commerce, finanzas, tecnología, restaurantes, portfolio, agencias, dashboards, landing, web app); 8 métricas ponderadas con evidencia; y la definición de éxito del plan verificada en 10 checks.",
  "Adapter OpenDesign (adapter-opendesign.ts): PeticiónForja → OpenDesignRequest → runtime → OpenDesignArtifact → Evaluación FORJA. RuntimeLocal ejecuta el MVP completo SIN red ni OpenDesign instalado; el día del fork, se enchufa sin tocar nada más.",
];
